clear
clc
close all
load('D:\Data\EPISL\Processed\AutoArti\P207_EPISL_Session1.mat', 'SmoothPower', 'Frequencies')


settings = struct(...
    'peak_width_limits', [0.5, 12], ...
    'max_n_peaks', Inf, ...
    'min_peak_height', 0.1, ... % NB: original fooof uses .1, but these lines don't do much; might be mistake?
    'peak_threshold', 2, ... % multiply STD of remaining signal to determine if any peaks left in signal
    'aperiodic_mode', 'fixed', ... % fixed or knee
    'verbose', true, ...
    'debug', false, ...
    'freqs', [], ...
    'power_spectrum', [], ...
    'freq_range', [], ...
    'freq_res', [], ...
    'modeled_spectrum', [], ...
    'aperiodic_params', [NaN, NaN], ...
    'peak_params', [], ...
    'gaussian_params', [], ...
    'r_squared', NaN, ...
    'error', NaN, ...
    'fit_error', false, ...
    'error_msg', '');

tic;FooofModelMat = oscip.specparam_matlab(Frequencies, squeeze(SmoothPower(80, 100, :)), [3 40], settings);toc
tic;FooofModel = fooof(Frequencies, squeeze(SmoothPower(80, 100, :)), [3 40], settings, true);toc
figure;plot(FooofModel.freqs, FooofModel.fooofed_spectrum)
hold on
plot(FooofModelMat.freqs, FooofModelMat.modeled_spectrum)