function settings = check_settings(settings)
% froom fooof_mat wrapper

    % Set defaults for all settings
    defaults = struct(...
        'peak_width_limits', [0.5, 12], ...
        'max_n_peaks', Inf, ...
        'min_peak_height', 0.0, ...
        'peak_threshold', 2.0, ...
        'aperiodic_mode', 'fixed', ...
        'verbose', true);

    % Overwrite any non-existent or nan settings with defaults
    for field = fieldnames(defaults)'
        if ~isfield(settings, field) || all(isnan(settings.(field{1})))
            settings.(field{1}) = defaults.(field{1});
        end
    end